[user]
name = "Warre"
email = "warre.dujardin@techwolf.ai"

[git]
push-new-bookmark = true
sign-on-push = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'



[aliases]
l = ["log"]
sq = ["squash"]
gp = ["git", "push"]
gpn = ["git", "push", "-N", "-r", "@ | @-"]
gf = ["git", "fetch"]
gcl = ["git", "clone", "--colocate"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "@"]
dm = ["describe", "-m"]


[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[ui]
editor = "nvim"
# diff-editor = "vscode"
merge-editor = "vscode"
